name: Run Promotors Script

on:
  schedule:
    # Run every 3 minutes between 3:45 AM and 10:05 AM UTC on weekdays (Monday to Friday)
    - cron: '*/3 3-10 * * 1-5'
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}  # Ensure this matches the secret's name in GitHub
        run: python promotorsTS.py  # Ensure the path to the script is correct
